apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: notebook-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: "letsencrypt-issuer"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tls.secretName }}

  ingressClassName: nginx

  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /notebook(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: notebook-service
                port:
                  number: 80
