apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notebook-server-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: autonmis-efs-sc
