apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: autonmis-cert
  namespace: autonmis
spec:
  secretName: autonmis-tls-secret
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  dnsNames:
    - kuber.autonmis.com
